require 'minitest/autorun'
require 'minitest_rails_tools/application_integration'
require 'minitest_rails_tools/association_matchers'
require 'minitest_rails_tools/expectations'
require 'minitest_rails_tools/helper_extension'
require 'minitest_rails_tools/validation_matchers'
